import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Suspense } from "react";
import Loader from "./components/Loader";

const poppins = Poppins({
  variable: "--poppins",
  subsets: ["latin"],
  weight: "100"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <Suspense fallback={<Loader />}>
          <Navbar />
            {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
